name = "educhainmag/aiken_contract"
version = "0.0.0"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for educhainmag"

[repository]
user = "user"
project = "project"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.0.0"
source = "github"